##########
#######
####

# Possible placeholders in this plugin
# PLACEHOLDERS
# {PLAYER} = returns to the name of the player who is related to event
# {MESSAGE} = returns to the message from player

##################################
#          Player Swear          #
##################################


# replace the words by a character
# not that if this is enabled,
# the letter of the word will be replace to the character you input
replace: true

# the character to replace to a word test = "****"
replacement: '*'

# Block player from chat if they swear
block: false


######################################
#          Chat Cooldown             #
######################################

chatCooldown: true

# Input chat interval ( seconds )
chatInterval: 3

######################################
#             Anti Spam              #
######################################

# After having 5 counts of message it will give a delay
chatLimit: 5

# seconds delay
chatDelay: 3

######################################
#            Staff Chat              #
######################################

staffChat: true

staffChatFormat: '&8[&6StaffChat&8] &6{PLAYER} : &r{MESSAGE}'

######################################
#            Broadcast               #
######################################

# {PLAYER} might be console if the sender of the command is console
broadcastFormat: '&8[&6Broadcast&8] &6{PLAYER} : &r{MESSAGE}'

######################################
#           Clear Chat               #
######################################

# Clear chat output message will be given to player if it is enabled
# You can always modify the output message in lang.yml

clearChatOutputMessage: true

######################################
#            ChatColor               #
######################################

# enable this if you want to colorize chat when it contains color codes
# for color code list : http://www.minecraftforum.net/forums/support/server-support/tutorials-and-faqs/1940467-bukkit-colour-codes
chatColorEffect: true

######################################
#            Anti Ads                #
######################################

# enable this if you want to add anti advertisement
antiAd: true

# if a player chat something match this with dots (.)
# will be cancelled and known as advertising
# such as play.test.test
# mc.com.org
# and so on
websiteMatcher:
 - 'com'
 - 'org'
 - 'net'
 - 'mc'
 - 'play'

 ######################################
 #          Chat Format               #
 ######################################

# Enable this plugin to format your chat if you want
chatFormatting: true

# the format
# {PLAYER} , {RANK} = PEX rank or GroupManager rank
# {MESSAGE} returns to player message
# {DISPLAYNAME} returns to player displayname
chatFormat: '&7{PLAYER} &7: &f{MESSAGE}'

# format based on the permission
groupFormat:

  # chatmanager.op is default, this will check if the player is op not the permission
  op: '&8[&cOperator&8] &c{PLAYER} &7: &f{MESSAGE}'

  # else if the player is not op check other permission
  # giving a permission chatmanager.builder will give them this prefix
  builder: '&8[&1Builder&8] &a{PLAYER} &7: &f{MESSAGE}'

  # If the player is not permitted it will direct to the default chatFormat

 ######################################
 #          Join And Quit             #
 ######################################

# Make it false if you do not want to enable this feature
# PlaceHolders
# {PLAYER} return to player name
# {DISPLAYNAME} return player displayname
# {SERVER} return to server name
# {MAXPLAYER} return to max player count
# {ONLINE} return to online players
# {WORLD} return to world name
joinListener: true

# Color code is supported
# if the player is not permitted with custom join message
# then this is the default one
joinMessage: '&bWelcome back &7{DISPLAYNAME} &benjoy your day'

# First join message
firstJoinMessage:

  # This is for default player
  default: '&bWelcme &7{DISPLAYNAME} &bto the server'

  # I assume that you want a custom one for specific player so input their name
  LifeonBlack: '&bWelcome developer :)'

# having no permission below will fire the joinMessage above
customJoinMessage:

  # This is only for op
  op: '&bWelcome the operator of the server'

  # This is for permitted chatmanager.join.owner
  owner: '&bWelcome the owner of the server'

quitListener: true

# Color code is supported
# if the player is not permitted with custom quit message
# then this is the default one
quitMessage: '&7[-]{DISPLAYNAME}'

# having no permission below will fire the quitMessage above
customQuitMessage:

  # This is for only op
  op: '&cOperator left'

  # This is for permitted chatmanager.quit.owner
  owner: '&cThe owner left'

 ######################################
 #            Anti Cheat              #
 ######################################

# This feature is only special
# Enable this feature if you want
antiCheat: true

# on player interact
# this will check if the player is interacting faster, then warn player
playerInteract: true

# on player break
# if the player break many blocks faster, then warn the player
# this is system is smart, it will not warn the player when breaking just 10 blocks :)
playerBreak: true

# on player click on inventory
# if it is fast it will close and warn the player
playerClickInventory: true

# if player is hitting another entity faster it will warn the player
playerDamageEntity: true